version: "3"

services:

  app:
    container_name: app
    build: .
    image: php:7.2-apache
    restart: unless-stopped   
    ports:
      - "3500:80"
    volumes:
      - .:/var/www/html
    networks:
      - net

networks:
  net:
